<table>
    <tr>
        <td>Nickname</td>
        <td>${user.nickname}</td>
    </tr>
    <tr>
        <td>Name</td>
        <td>${user.name}</td>
    </tr>
    <tr>
        <td>Surname</td>
        <td>${user.surname}</td>
    </tr>
    <tr>
        <td>Email</td>
        <td>${user.email}</td>
    </tr>
    <tr>
        <td>Role</td>
        <td>${user.role}</td>
    </tr>
</table>
